---
- name: Deploy VM from template in vCenter
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.vmware
  
  vars:
    # vCenter Connection Details
    vcenter_hostname: "10.0.0.176"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "P@ssw0rd24"
    
    # vCenter Infrastructure
    datacenter_name: "MYLAB-DC"
    cluster_name: "MYLAB-Cluster"
    datastore_name: "datastore1"
    vm_folder: "vm"
    
    # VM Configuration
    template_name: "BASELINE 120"
    vm_name: "test01 27"
    guest_os: "rhel9_64Guest"
    
    # Hardware Specifications
    memory_mb: 2048
    num_cpus: 1
    
    # Network Configuration
    network_name: "VM Network"
    vm_ip: "10.0.0.27"
    vm_netmask: "255.255.255.0"
    vm_gateway: "10.0.0.1"
    dns_servers:
      - "10.0.0.11"
      - "8.8.8.8"
    
    # Guest Customization
    vm_hostname: "{{ vm_name }}"
    vm_domain: "henogez.com"

  tasks:
    - name: Display VM deployment configuration
      debug:
        msg:
          - "=========================================="
          - "VMware VM Deployment Configuration"
          - "=========================================="
          - "vCenter: {{ vcenter_hostname }}"
          - "Datacenter: {{ datacenter_name }}"
          - "Cluster: {{ cluster_name }}"
          - "Datastore: {{ datastore_name }}"
          - "Template: {{ template_name }}"
          - "VM Name: {{ vm_name }}"
          - "Folder: {{ vm_folder }}"
          - "Memory: {{ memory_mb }} MB"
          - "CPUs: {{ num_cpus }}"
          - "IP Address: {{ vm_ip }}"
          - "Gateway: {{ vm_gateway }}"
          - "Domain: {{ vm_domain }}"
          - "=========================================="

    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        state: poweredon
        guest_id: "{{ guest_os }}"
        hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
          scsi: paravirtual
        networks:
          - name: "{{ network_name }}"
            type: static
            ip: "{{ vm_ip }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
            dns_servers: "{{ dns_servers }}"
        customization:
          hostname: "{{ vm_hostname }}"
          domain: "{{ vm_domain }}"
      delegate_to: localhost
      register: vm_deploy

    - name: Display VM deployment result
      debug:
        msg: "VM {{ vm_name }} has been successfully deployed"
      when: vm_deploy.changed

    - name: Wait for VM to be accessible via SSH
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        delay: 30
        timeout: 300
        state: started
      register: ssh_wait
      ignore_errors: true

    - name: Display SSH availability
      debug:
        msg: "SSH is available on {{ vm_ip }}:22"
      when: ssh_wait is succeeded

    - name: Deployment Summary
      debug:
        msg:
          - "=========================================="
          - "VM Deployment Complete!"
          - "=========================================="
          - "VM Name: {{ vm_name }}"
          - "IP Address: {{ vm_ip }}"
          - "FQDN: {{ vm_hostname }}.{{ vm_domain }}"
          - "SSH Access: ssh root@{{ vm_ip }}"
          - "vCenter: {{ vcenter_hostname }}"
          - "=========================================="
