---
- name: Deploy VM from template in vCenter
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.vmware
  vars_files:
    - vault.yaml

  tasks:
  - name: Clone VM from template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false

      datacenter: "{{ datacenter_name }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      template: "{{ template_name }}"
      cluster: "{{ cluster_name }}"
      datastore: "{{ datastore_name }}"
      state: poweredon

      guest_id: "rhel8_64Guest"

      hardware:
        memory_mb: 2048
        num_cpus: 2
        scsi: paravirtual

      networks:
        - name: "VM Network"
          type: static
          ip: "10.0.0.18"
          netmask: "255.255.255.0"
          gateway: "10.0.0.1"
          dns_servers:
            - "10.0.0.11"
            - "8.8.8.8"

      customization:
        hostname: "{{ vm_name }}"
        domain: "henogez.com"

    delegate_to: localhost
