---
- name: Install and Configure DNS Server (BIND) on RHEL 9
  hosts: dns
  become: true
  vars:
    domain_name: "henogez.com"
    zone_file: "forward.henogez.com"
    dns_ip: "10.0.0.35"  # IP of the DNS server
    reverse_zone_name: "0.0.10.in-addr.arpa"
    reverse_zone_file: "reverse.henogez.com"
    host_last_octet: "35"
  tasks:

  - name: Install BIND and utilities
    dnf:
      name:
        - bind
        - bind-utils
      state: present

  - name: Enable and start named service
    systemd:
      name: named
      enabled: yes
      state: started

  - name: Ensure backup directory exists
    file:
      path: /etc/named.backups
      state: directory
      mode: '0755'

  - name: Backup named.conf with timestamp
    copy:
      src: /etc/named.conf
      dest: "/etc/named.backups/named.conf.{{ ansible_date_time.iso8601 }}"
      remote_src: yes
      mode: '0644'

  - name: Configure main BIND config
    copy:
      dest: /etc/named.conf
      content: |
        options {
            listen-on port 53 { 127.0.0.1; 10.0.0.35; };
            listen-on-v6 port 53 { ::1; };
            directory     "/var/named";
            dump-file     "/var/named/data/cache_dump.db";
            statistics-file "/var/named/data/named_stats.txt";
            memstatistics-file "/var/named/data/named_mem_stats.txt";
            secroots-file   "/var/named/data/named.secroots";
            recursing-file  "/var/named/data/named.recursing";
            allow-query     { any; };
            recursion yes;
            
            dnssec-enable yes;
            dnssec-validation yes;

            managed-keys-directory "/var/named/dynamic";

            pid-file "/run/named/named.pid";
            session-keyfile "/run/named/session.key";

            include "/etc/crypto-policies/back-ends/bind.config";
 
        };

        zone "{{ domain_name }}" IN {
            type master;
            file "{{ zone_file }}";
            allow-update { none; };
            allow-query { any; };
        };

  - name: Add reverse zone to named.conf
    blockinfile:
      path: /etc/named.conf
      marker: "# {mark} REVERSE ZONE BLOCK"
      block: |
        zone "{{ reverse_zone_name }}" IN {
            type master;
            file "{{ reverse_zone_file }}";
            allow-update { none; };
            allow-query { any; };
        };

        include "/etc/named.rfc1912.zones";
        include "/etc/named.root.key";

  - name: Create forward zone file
    copy:
      dest: /var/named/{{ zone_file }}
      owner: named
      group: named
      mode: '0644'
      content: |
        $TTL 86400
        @   IN  SOA     dns-01.{{ domain_name }}. root.{{ domain_name }}. (
                    2025060501 ; Serial
                    3600       ; Refresh
                    1800       ; Retry
                    604800     ; Expire
                    86400 )    ; Minimum TTL

            IN  NS      dns-01.{{ domain_name }}.
        dns-01 IN  A       {{ dns_ip }}
        www    IN  A       {{ dns_ip }}

  - name: Create reverse zone file
    copy:
      dest: /var/named/{{ reverse_zone_file }}
      owner: named
      group: named
      mode: '0644'
      content: |
        $TTL 86400
        @   IN  SOA     dns-01.{{ domain_name }}. root.{{ domain_name }}. (
                    2025060501 ; Serial
                    3600       ; Refresh
                    1800       ; Retry
                    604800     ; Expire
                    86400 )    ; Minimum TTL

            IN  NS      dns-01.{{ domain_name }}.
        {{ host_last_octet }} IN PTR    dns-01.{{ domain_name }}.

  #  - name: Allow DNS through firewalld
  #  firewalld:
  #    service: dns
  #    permanent: true
  #    state: enabled
  #    immediate: true

  - name: Restart named to apply zone changes
    systemd:
      name: named
      state: restarted

  - name: Verify named is running
    shell: systemctl is-active named
    register: named_status
    changed_when: false

  - name: Show named status
    debug:
      msg: "named service is {{ named_status.stdout }}"
